An error occurred while executing the following cell:
------------------
from tkinter.tix import Tree
from unicodedata import name
from absl import app
from absl import flags

try:
    import flax.linen as nn
except ModuleNotFoundError:
    %pip install flax
    import flax.linen as nn

from flax.training import train_state, checkpoints
import shutil
import jax.numpy as jnp
import jax
from jax import random
import numpy as np

try:
    import optax
except ModuleNotFoundError:
    %pip install optax
    import optax

try:
    import tensorflow as tf
except ModuleNotFoundError:
    %pip install tensorflow
    import tensorflow as tf

try:
    import tensorflow_datasets as tfds
except ModuleNotFoundError:
    %pip install tensorflow tensorflow_datasets
    import tensorflow_datasets as tfds


import scipy.io
import os
import math
from PIL import Image
import matplotlib.pyplot as plt

os.environ["XLA_PYTHON_CLIENT_PREALLOCATE"] = "False"
------------------

---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
/tmp/ipykernel_2752/3116938674.py in <module>
     10     import flax.linen as nn
     11 
---> 12 from flax.training import train_state, checkpoints
     13 import shutil
     14 import jax.numpy as jnp

~/miniconda3/envs/py37/lib/python3.7/site-packages/flax/training/checkpoints.py in <module>
     29 from flax import errors
     30 from flax import serialization
---> 31 from tensorflow.io import gfile  # pytype: disable=import-error
     32 
     33 

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/__init__.py in <module>
     35 import typing as _typing
     36 
---> 37 from tensorflow.python.tools import module_util as _module_util
     38 from tensorflow.python.util.lazy_loader import LazyLoader as _LazyLoader
     39 

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/__init__.py in <module>
     34 # pylint: disable=wildcard-import,g-bad-import-order,g-import-not-at-top
     35 
---> 36 from tensorflow.python import pywrap_tensorflow as _pywrap_tensorflow
     37 from tensorflow.python.eager import context
     38 

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/pywrap_tensorflow.py in <module>
     22 
     23 # Perform pre-load sanity checks in order to produce a more actionable error.
---> 24 self_check.preload_check()
     25 
     26 # pylint: disable=wildcard-import,g-import-not-at-top,unused-import,line-too-long

~/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/platform/self_check.py in preload_check()
     63     cpu_feature_guard_library = os.path.join(
     64         os.path.dirname(__file__), "../../core/platform/_cpu_feature_guard.so")
---> 65     ctypes.CDLL(cpu_feature_guard_library)

~/miniconda3/envs/py37/lib/python3.7/ctypes/__init__.py in __init__(self, name, mode, handle, use_errno, use_last_error)
    362 
    363         if handle is None:
--> 364             self._handle = _dlopen(self._name, mode)
    365         else:
    366             self._handle = handle

OSError: /github/home/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/platform/../../core/platform/_cpu_feature_guard.so: cannot open shared object file: No such file or directory
OSError: /github/home/miniconda3/envs/py37/lib/python3.7/site-packages/tensorflow/python/platform/../../core/platform/_cpu_feature_guard.so: cannot open shared object file: No such file or directory
